export const COMPANY_DESCRIPTIONS: Record<string, string> = {
  AAPL: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. Apple designs, develops, and sells consumer electronics, computer software, and online services. The company is best known for its iPhone smartphones, iPad tablets, Mac computers, Apple Watch smartwatches, and AirPods wireless earbuds. Apple also operates digital content platforms including the App Store, Apple Music, iCloud, and Apple TV+, creating a highly integrated ecosystem of hardware, software, and services.",
  ASML: "ASML Holding N.V. is a Dutch-based global leader in semiconductor equipment, specializing in advanced photolithography systems that are critical for manufacturing integrated circuits. Founded in 1984 and headquartered in Veldhoven, the company is the sole supplier of cutting-edge extreme ultraviolet (EUV) lithography tools and a dominant provider of deep ultraviolet (DUV) systems, complemented by metrology, inspection, and computational lithography software solutions. ASML's systems enable chipmakers worldwide to produce smaller, more powerful, and more energy-efficient chips used across consumer electronics, data centers, automotive, and industrial applications, underpinning key technology trends such as AI and high-performance computing.",
  MSFT: "Microsoft Corporation is an American multinational technology company that develops, licenses, and supports a wide range of software products, services, and devices. Best known for the Windows operating system and Office productivity suite, Microsoft has evolved into a leading cloud computing provider through Azure, while also offering enterprise solutions, gaming hardware and services (Xbox, Game Pass), LinkedIn professional networking, and artificial intelligence technologies integrated across its product portfolio.",
  NVDA: "NVIDIA Corporation is an American technology company that designs graphics processing units (GPUs) for gaming, professional visualization, data centers, and automotive markets. Founded in 1993 and headquartered in Santa Clara, California, NVIDIA has become a dominant force in AI computing, high-performance computing, and accelerated computing platforms. The company's GPUs power everything from gaming PCs to the world's most advanced AI supercomputers, making NVIDIA a critical enabler of artificial intelligence, machine learning, autonomous vehicles, and scientific research.",
  GOOGL: "Alphabet Inc. is an American multinational conglomerate and the parent company of Google and several former Google subsidiaries. Through Google, Alphabet dominates online search, digital advertising, mobile operating systems (Android), web browsers (Chrome), and cloud computing. The company also invests in emerging technologies through divisions like Waymo (autonomous vehicles), Verily (life sciences), and DeepMind (artificial intelligence), while generating the majority of its revenue from advertising across Search, YouTube, and the Google Display Network.",
  TSLA: "Tesla, Inc. is an American electric vehicle and clean energy company founded in 2003 and headquartered in Austin, Texas. Tesla designs and manufactures electric cars, battery energy storage systems, solar panels, and related products and services. The company operates automotive production facilities around the world and has built a proprietary Supercharger network for fast charging. Tesla is also developing autonomous driving technology and robotics, positioning itself as a leader in sustainable transportation and energy solutions.",
};

